macro(set_enabled_languages_file_globs)
  get_property(PROJECT_ENABLED_LANGUAGES GLOBAL PROPERTY ENABLED_LANGUAGES)
  foreach(PROJECT_ENABLED_LANGUAGE ${PROJECT_ENABLED_LANGUAGES})
    list(TRANSFORM "CMAKE_${PROJECT_ENABLED_LANGUAGE}_SOURCE_FILE_EXTENSIONS"
      PREPEND "*."
      OUTPUT_VARIABLE "CMAKE_${PROJECT_ENABLED_LANGUAGE}_SOURCE_FILE_GLOB_EXPRESSIONS"
    )
    list(TRANSFORM "CMAKE_${PROJECT_ENABLED_LANGUAGE}_IGNORE_EXTENSIONS"
      PREPEND "*."
      OUTPUT_VARIABLE "CMAKE_${PROJECT_ENABLED_LANGUAGE}_IGNORE_GLOB_EXPRESSIONS"
    )
  endforeach(PROJECT_ENABLED_LANGUAGE)
endmacro(set_enabled_languages_file_globs)

macro(file_glob_enabled_languages_source_files)
  get_property(PROJECT_ENABLED_LANGUAGES GLOBAL PROPERTY ENABLED_LANGUAGES)
  foreach(PROJECT_ENABLED_LANGUAGE ${PROJECT_ENABLED_LANGUAGES})
    file(GLOB "PROJECT_${PROJECT_ENABLED_LANGUAGE}_SOURCE_FILES"
      RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}
      ${CMAKE_${PROJECT_ENABLED_LANGUAGE}_SOURCE_FILE_GLOB_EXPRESSIONS}
    )
    if(CMAKE_${PROJECT_ENABLED_LANGUAGE}_IGNORE_GLOB_EXPRESSIONS)
      file(GLOB "PROJECT_${PROJECT_ENABLED_LANGUAGE}_IGNORES"
        RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}
        ${CMAKE_${PROJECT_ENABLED_LANGUAGE}_IGNORE_GLOB_EXPRESSIONS}
      )
      list(APPEND PROJECT_ANY_LANG_IGNORES ${PROJECT_${PROJECT_ENABLED_LANGUAGE}_IGNORES})
      list(REMOVE_ITEM "PROJECT_${PROJECT_ENABLED_LANGUAGE}_SOURCE_FILES"
        ${PROJECT_${PROJECT_ENABLED_LANGUAGE}_IGNORES}
      )
    endif(CMAKE_${PROJECT_ENABLED_LANGUAGE}_IGNORE_GLOB_EXPRESSIONS)
    list(APPEND PROJECT_ANY_LANG_SOURCE_FILES ${PROJECT_${PROJECT_ENABLED_LANGUAGE}_SOURCE_FILES})
  endforeach(PROJECT_ENABLED_LANGUAGE)
  list(REMOVE_DUPLICATES PROJECT_ANY_LANG_SOURCE_FILES)
  list(REMOVE_DUPLICATES PROJECT_ANY_LANG_IGNORES)
  list(REMOVE_ITEM PROJECT_ANY_LANG_IGNORES ${PROJECT_ANY_LANG_SOURCE_FILES})
endmacro(file_glob_enabled_languages_source_files)

macro(set_asm_masm_source_files_language_property)
  set_source_files_properties(
    ${PROJECT_ASM_MASM_SOURCE_FILES}
    PROPERTIES LANGUAGE ASM_MASM
  )
endmacro(set_asm_masm_source_files_language_property)
