function(set_file_globs)
  if(ARGC GREATER 0)
    set(VAR_PREFIX ${ARGV0})
  else()
    unset(VAR_PREFIX)
  endif()
  if(ARGC GREATER 1)
    set(CONFIGURE_DEPENDS ${ARGV1})
  else()
    unset(CONFIGURE_DEPENDS)
  endif()
  if(NOT VAR_PREFIX)
    set(VAR_PREFIX PROJECT)
  endif()
  unset(RETURN_LANGUAGE_VARIABLES)
  foreach(CMAKE_ENABLED_LANGUAGE IN LISTS CMAKE_ENABLED_LANGUAGES)
    if(CONFIGURE_DEPENDS)
      file(GLOB "${VAR_PREFIX}_${CMAKE_ENABLED_LANGUAGE}_SOURCE_FILES"
        ${CONFIGURE_DEPENDS} ${CMAKE_${CMAKE_ENABLED_LANGUAGE}_SOURCE_FILE_LOCAL_GLOBS}
      )
    else()
      file(GLOB "${VAR_PREFIX}_${CMAKE_ENABLED_LANGUAGE}_SOURCE_FILES"
        ${CMAKE_${CMAKE_ENABLED_LANGUAGE}_SOURCE_FILE_LOCAL_GLOBS}
      )
    endif()
    list(APPEND ${VAR_PREFIX}_ANY_LANG_SOURCE_FILES
      ${${VAR_PREFIX}_${CMAKE_ENABLED_LANGUAGE}_SOURCE_FILES}
    )
    list(APPEND RETURN_LANGUAGE_VARIABLES
      "${VAR_PREFIX}_${CMAKE_ENABLED_LANGUAGE}_SOURCE_FILES"
    )
  endforeach()
  if(CONFIGURE_DEPENDS)
    file(GLOB ${VAR_PREFIX}_ANY_LANG_IGNORE_FILES
      ${CONFIGURE_DEPENDS} ${CMAKE_ANY_LANG_IGNORE_LOCAL_GLOBS}
    )
  else()
    file(GLOB ${VAR_PREFIX}_ANY_LANG_IGNORE_FILES
      ${CMAKE_ANY_LANG_IGNORE_LOCAL_GLOBS}
    )
  endif()
  return(PROPAGATE
    ${VAR_PREFIX}_ANY_LANG_SOURCE_FILES
    ${VAR_PREFIX}_ANY_LANG_IGNORE_FILES
    ${RETURN_LANGUAGE_VARIABLES}
  )
endfunction(set_file_globs)
