function(set_enabled_language_file_extensions)
  get_property(CMAKE_ENABLED_LANGUAGES GLOBAL PROPERTY ENABLED_LANGUAGES)
  unset(RETURN_LANGUAGE_VARIABLES)
  foreach(CMAKE_ENABLED_LANGUAGE IN LISTS CMAKE_ENABLED_LANGUAGES)
    list(APPEND CMAKE_ANY_LANG_SOURCE_FILE_EXTENSIONS
      ${CMAKE_${CMAKE_ENABLED_LANGUAGE}_SOURCE_FILE_EXTENSIONS}
    )
    list(APPEND CMAKE_ANY_LANG_IGNORE_EXTENSIONS
      ${CMAKE_${CMAKE_ENABLED_LANGUAGE}_IGNORE_EXTENSIONS}
    )
    list(TRANSFORM "CMAKE_${CMAKE_ENABLED_LANGUAGE}_SOURCE_FILE_EXTENSIONS"
      PREPEND "*."
      OUTPUT_VARIABLE "CMAKE_${CMAKE_ENABLED_LANGUAGE}_SOURCE_FILE_LOCAL_GLOBS"
    )
    list(TRANSFORM "CMAKE_${CMAKE_ENABLED_LANGUAGE}_IGNORE_EXTENSIONS"
      PREPEND "*."
      OUTPUT_VARIABLE "CMAKE_${CMAKE_ENABLED_LANGUAGE}_IGNORE_LOCAL_GLOBS"
    )
    list(APPEND RETURN_LANGUAGE_VARIABLES
      "CMAKE_${CMAKE_ENABLED_LANGUAGE}_SOURCE_FILE_LOCAL_GLOBS"
      "CMAKE_${CMAKE_ENABLED_LANGUAGE}_IGNORE_LOCAL_GLOBS"
    )
  endforeach()
  list(REMOVE_DUPLICATES CMAKE_ANY_LANG_SOURCE_FILE_EXTENSIONS)
  list(REMOVE_ITEM CMAKE_ANY_LANG_IGNORE_EXTENSIONS
    ${CMAKE_ANY_LANG_SOURCE_FILE_EXTENSIONS}
  )
  list(REMOVE_DUPLICATES CMAKE_ANY_LANG_IGNORE_EXTENSIONS)
  list(TRANSFORM "CMAKE_ANY_LANG_SOURCE_FILE_EXTENSIONS"
    PREPEND "*."
    OUTPUT_VARIABLE "CMAKE_ANY_LANG_SOURCE_FILE_LOCAL_GLOBS"
  )
  list(TRANSFORM "CMAKE_ANY_LANG_IGNORE_EXTENSIONS"
    PREPEND "*."
    OUTPUT_VARIABLE "CMAKE_ANY_LANG_IGNORE_LOCAL_GLOBS"
  )
  return(PROPAGATE
    CMAKE_ENABLED_LANGUAGES
    CMAKE_ANY_LANG_SOURCE_FILE_EXTENSIONS
    CMAKE_ANY_LANG_IGNORE_EXTENSIONS
    CMAKE_ANY_LANG_SOURCE_FILE_LOCAL_GLOBS
    CMAKE_ANY_LANG_IGNORE_LOCAL_GLOBS
    ${RETURN_LANGUAGE_VARIABLES}
  )
endfunction()
