macro(set_file_extensions_local_globs)
  get_property(PROJECT_ENABLED_LANGUAGES GLOBAL PROPERTY ENABLED_LANGUAGES)

  list(APPEND CMAKE_ASM_MASM_SOURCE_FILE_EXTENSIONS "ASM")
  list(APPEND CMAKE_ASM_MASM_IGNORE_EXTENSIONS "I" "INC")

  foreach(PROJECT_ENABLED_LANGUAGE ${PROJECT_ENABLED_LANGUAGES})
    list(APPEND CMAKE_ANY_LANG_SOURCE_FILE_EXTENSIONS
      ${CMAKE_${PROJECT_ENABLED_LANGUAGE}_SOURCE_FILE_EXTENSIONS}
    )
    list(APPEND CMAKE_ANY_LANG_IGNORE_EXTENSIONS
      ${CMAKE_${PROJECT_ENABLED_LANGUAGE}_IGNORE_EXTENSIONS}
    )
    list(TRANSFORM "CMAKE_${PROJECT_ENABLED_LANGUAGE}_SOURCE_FILE_EXTENSIONS"
      PREPEND "*."
      OUTPUT_VARIABLE "CMAKE_${PROJECT_ENABLED_LANGUAGE}_SOURCE_FILE_LOCAL_GLOBS"
    )
    list(TRANSFORM "CMAKE_${PROJECT_ENABLED_LANGUAGE}_IGNORE_EXTENSIONS"
      PREPEND "*."
      OUTPUT_VARIABLE "CMAKE_${PROJECT_ENABLED_LANGUAGE}_IGNORE_LOCAL_GLOBS"
    )
  endforeach()
  list(REMOVE_DUPLICATES CMAKE_ANY_LANG_SOURCE_FILE_EXTENSIONS)
  list(REMOVE_ITEM CMAKE_ANY_LANG_IGNORE_EXTENSIONS ${CMAKE_ANY_LANG_SOURCE_FILE_EXTENSIONS})
  list(REMOVE_DUPLICATES CMAKE_ANY_LANG_IGNORE_EXTENSIONS)
  list(TRANSFORM "CMAKE_ANY_LANG_SOURCE_FILE_EXTENSIONS"
    PREPEND "*."
    OUTPUT_VARIABLE "CMAKE_ANY_LANG_SOURCE_FILE_LOCAL_GLOBS"
  )
  list(TRANSFORM "CMAKE_ANY_LANG_IGNORE_EXTENSIONS"
    PREPEND "*."
    OUTPUT_VARIABLE "CMAKE_ANY_LANG_IGNORE_LOCAL_GLOBS"
  )
endmacro()
