function(project_component
  PROJECT_COMPONENT_NAME
  PROJECT_COMPONENT_INCLUDE_DIRS
)
  set(PROJECT_COMPONENT_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR})
  unset(PROJECT_COMPONENT_ABSOLUTE_INCLUDE_DIRS)
  foreach(PROJECT_COMPONENT_INCLUDE_DIR IN LISTS PROJECT_COMPONENT_INCLUDE_DIRS)
    if(PROJECT_COMPONENT_INCLUDE_DIR)
      cmake_path(ABSOLUTE_PATH PROJECT_COMPONENT_INCLUDE_DIR NORMALIZE)
      list(APPEND PROJECT_COMPONENT_ABSOLUTE_INCLUDE_DIRS
        ${PROJECT_COMPONENT_INCLUDE_DIR}
      )
    endif()
  endforeach()
  set(PROJECT_COMPONENT_INCLUDE_DIRS ${PROJECT_COMPONENT_ABSOLUTE_INCLUDE_DIRS})
  # cmake_path(RELATIVE_PATH PROJECT_COMPONENT_SOURCE_DIR
  #   OUTPUT_VARIABLE PROJECT_COMPONENT_RELATIVE_SOURCE_DIR
  # )
  cmake_path(ABSOLUTE_PATH PROJECT_COMPONENT_SOURCE_DIR NORMALIZE)
  return(PROPAGATE
    PROJECT_COMPONENT_NAME
    PROJECT_COMPONENT_SOURCE_DIR
    PROJECT_COMPONENT_INCLUDE_DIRS
  )
endfunction(project_component)
