include(file_glob_target)

function(project_component)
  if(ARGC GREATER 0)
    set(PROJECT_COMPONENT_NAME ${ARGV0})
  else()
    unset(PROJECT_COMPONENT_NAME)
  endif()
  if(ARGC GREATER 1)
    set(PROJECT_COMPONENT_INCLUDE_DIRS ${ARGV1})
  else()
    unset(PROJECT_COMPONENT_INCLUDE_DIRS)
  endif()
  if(ARGC GREATER 2)
    set(CONFIGURE_DEPENDS ${ARGV2})
  else()
    unset(CONFIGURE_DEPENDS)
  endif()
  if(NOT PROJECT_COMPONENT_NAME OR PROJECT_COMPONENT_NAME STREQUAL DEFAULT)
    cmake_path(GET CMAKE_CURRENT_SOURCE_DIR FILENAME PROJECT_COMPONENT_NAME)
  endif()
  set(PROJECT_COMPONENT_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR})
  unset(PROJECT_COMPONENT_ABSOLUTE_INCLUDE_DIRS)
  foreach(PROJECT_COMPONENT_INCLUDE_DIR IN LISTS PROJECT_COMPONENT_INCLUDE_DIRS)
    if(PROJECT_COMPONENT_INCLUDE_DIR)
      cmake_path(ABSOLUTE_PATH PROJECT_COMPONENT_INCLUDE_DIR NORMALIZE)
      list(APPEND PROJECT_COMPONENT_ABSOLUTE_INCLUDE_DIRS
        ${PROJECT_COMPONENT_INCLUDE_DIR}
      )
    endif()
  endforeach()
  set(PROJECT_COMPONENT_INCLUDE_DIRS ${PROJECT_COMPONENT_ABSOLUTE_INCLUDE_DIRS})
  set_file_globs(PROJECT_COMPONENT ${CONFIGURE_DEPENDS})
  unset(RETURN_LANGUAGE_VARIABLES)
  foreach(CMAKE_ENABLED_LANGUAGE IN LISTS CMAKE_ENABLED_LANGUAGES)
  list(APPEND RETURN_LANGUAGE_VARIABLES
    "PROJECT_COMPONENT_${CMAKE_ENABLED_LANGUAGE}_SOURCE_FILES"
  )
  endforeach()
  return(PROPAGATE
    PROJECT_COMPONENT_NAME
    PROJECT_COMPONENT_SOURCE_DIR
    PROJECT_COMPONENT_INCLUDE_DIRS
    PROJECT_COMPONENT_ANY_LANG_SOURCE_FILES
    PROJECT_COMPONENT_ANY_LANG_IGNORE_FILES
    ${RETURN_LANGUAGE_VARIABLES}
  )
endfunction(project_component)

function(project_subcomponent)
  if(ARGC GREATER 0)
    set(CONFIGURE_DEPENDS ${ARGV0})
  else()
    unset(CONFIGURE_DEPENDS)
  endif()
  cmake_path(RELATIVE_PATH CMAKE_CURRENT_SOURCE_DIR
    BASE_DIRECTORY ${PROJECT_COMPONENT_SOURCE_DIR}
    OUTPUT_VARIABLE PROJECT_SUBCOMPONENT_NAME
  )
  string(REPLACE "/" "_" PROJECT_SUBCOMPONENT_NAME ${PROJECT_SUBCOMPONENT_NAME})
  string(PREPEND PROJECT_SUBCOMPONENT_NAME ${PROJECT_COMPONENT_NAME} "_")
  set_file_globs(PROJECT_SUBCOMPONENT ${CONFIGURE_DEPENDS})
  unset(RETURN_LANGUAGE_VARIABLES)
  foreach(CMAKE_ENABLED_LANGUAGE IN LISTS CMAKE_ENABLED_LANGUAGES)
  list(APPEND RETURN_LANGUAGE_VARIABLES
    "PROJECT_SUBCOMPONENT_${CMAKE_ENABLED_LANGUAGE}_SOURCE_FILES"
  )
  endforeach()
  set(PROJECT_SUBCOMPONENT_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR})
  set(PROJECT_SUBCOMPONENT_INCLUDE_DIRS
    ${PROJECT_COMPONENT_INCLUDE_DIRS}
    ${PROJECT_COMPONENT_SOURCE_DIR}
  )
  return(PROPAGATE
    PROJECT_SUBCOMPONENT_NAME
    PROJECT_SUBCOMPONENT_SOURCE_DIR
    PROJECT_SUBCOMPONENT_INCLUDE_DIRS
    PROJECT_SUBCOMPONENT_ANY_LANG_SOURCE_FILES
    PROJECT_SUBCOMPONENT_ANY_LANG_IGNORE_FILES
    ${RETURN_LANGUAGE_VARIABLES}
  )
endfunction(project_subcomponent)
